version: 2.1
executors:
  unity:
    docker:
      - image: gableroux/unity3d:2020.1.0a21
commands:
  activate:
    steps:
      - run:
          name: "Activate Unity Licence File"
          command: |
            mkdir -p /root/.cache/unity3d
            mkdir -p /root/.local/share/unity3d/Unity/

            if [[ -z $"ACTIVATION_ULF_ENC" ]]; then
              echo "ACTIVATION_ULF_ENC is missing. You must provide the base64 encoded  ULF licence file contents."
              exit 1
            fi

            echo
            echo "Decoding and writing licence file to /root/.local/share/unity3d/Unity/Unity_lic.ulf"
            echo

            cat $ACTIVATION_ULF_ENC | base64 --decode > /root/.local/share/unity3d/Unity/Unity_lic.ulf
  run_tests:
    steps:
      - run:
          name: Testing
          command: |
            set -x

            echo "Testing for $TEST_PLATFORM"

            ${UNITY_EXECUTABLE:-xvfb-run --auto-servernum --server-args='-screen 0 640x480x24' /opt/Unity/Editor/Unity} \
              -projectPath $(pwd) \
              -runTests \
              -testPlatform $TEST_PLATFORM \
              -testResults $(pwd)/$TEST_PLATFORM-results.xml \
              -logFile /dev/stdout \
              -batchmode

            UNITY_EXIT_CODE=$?

            if [ $UNITY_EXIT_CODE -eq 0 ]; then
              echo "Run succeeded, no failures occurred";
            elif [ $UNITY_EXIT_CODE -eq 2 ]; then
              echo "Run succeeded, some tests failed";
            elif [ $UNITY_EXIT_CODE -eq 3 ]; then
              echo "Run failure (other failure)";
            else
              echo "Unexpected exit code $UNITY_EXIT_CODE";
            fi

            cat $(pwd)/$TEST_PLATFORM-results.xml | grep test-run | grep Passed
            exit $UNITY_TEST_EXIT_CODE
            
jobs:
  UnityTests:
    executor: unity
    steps:
      - run:
          name: Demo Unity
          command: echo "First commit"
      - activate
      - run_tests

workflows:
  Unity_Test_Deploy:
    jobs:
      - UnityTests