version: 2.1
executors:
  unity:
    docker:
      - image: gableroux/unity3d:2021.1.15f1

commands:
  activate:
    steps:
      - run:
          name: "Activate Unity Licence File"
          command: |
            mkdir -p /root/.cache/unity3d
            mkdir -p /root/.local/share/unity3d/Unity/

            if [[ -z $"ACTIVATION_ULF_ENC" ]]; then
              echo "ACTIVATION_ULF_ENC is missing. You must provide the base64 encoded  ULF licence file contents."
              exit 1
            fi

            echo
            echo "Decoding and writing licence file to /root/.local/share/unity3d/Unity/Unity_lic.ulf"
            echo

            cat $ACTIVATION_ULF_ENC | base64 --decode > /root/.local/share/unity3d/Unity/Unity_lic.ulf
 
jobs:
  UnityTests:
    executor: unity
    steps:
      - run:
          name: Demo Unity
          command: echo "First commit"
      - activate

workflows:
  Unity_Test_Deploy:
    jobs:
      - UnityTests